### ISSUE TITLE
Transparecy Theme broken as of Discord 0.0.298

### ISSUE THREAD

**Issue by Nexaii** [HoLLy-HaCKeR/BetterDiscord-Themes-and-Plugins#6]
Sadly the recent update has broken this otherwise fantastic theme.

**Comment by holly-hacker** [comment]
Mind being a bit more specific? Not saying I'll fix it (I have no interest in BetterDiscord anymore), but it's still nice to know what exactly is broken.

**Comment by Nexaii** [comment]
Ah strange, I edited the subject earlier to specifically say what broke but it for whatever reason didn't take. 

Both the transparency theme and transparency patcher seem to be broken. Both are enabled etc. Quick example: https://puu.sh/x7NFO/176bbe7477.png

**Comment by holly-hacker** [comment]
Seems like an issue similar to .layer. I may look at it tomorrow but I'm not promising anything.

**Comment by amateurre** [comment]
hopefully this gets fixed.. i tried it yesterday and it worked one time, but i needed to reinstall discord so yeah, it screwed up, and i'm stuck with a kinda clean black theme.

**Comment by ghost** [comment]
Holding thumbs for it to get fixed too!

**Comment by holly-hacker** [comment]
Try [this version](https://github.com/Akuba-/BetterDiscord-Themes-and-Plugins/blob/master/Plugins/transparency_patcher.plugin.js) from @Akuba-, it should work. I don't want to test it since I don't want BetterDiscord to run on my computer but if this works I'll merge it.

**Comment by holly-hacker** [comment]
So yeah, please report back if it works.

**Comment by techchrism** [comment]
This fixed the issue on my system, thank you!

**Comment by holly-hacker** [comment]
Okay, I'll merge it into this repo yet.

**Comment by Hippyrip** [comment]
Is this theme still working as of now? Please let me know. Spent all weekend trying to get this to work. Some aspects of it works minus the transparent background and what not.

**Comment by Akuba-** [comment]
I haven't got it to work with the latest Discord update but I had no time to take a closer look on this yet.

**Comment by Hippyrip** [comment]
Please let me know if you need any help! I am a nooby but i will do what ever it takes to help and get this running ! :)
